--DROP TABLE IF EXISTS COMMITTEES;
--DROP TABLE IF EXISTS FORMED_COMMITTEES;
--DROP TABLE IF EXISTS COMMITTEE_MEMBERS;
--DROP TABLE IF EXISTS MEMBER_ROLES;
--DROP TABLE IF EXISTS EMPLOYEES;
--DROP SEQUENCE IF EXISTS CMR_ROLE_ID_SEQ;


CREATE TABLE BASSAM_COMMITTEES
(
    CC_SID     BIGINT       NOT NULL,
    CC_AR_NAME VARCHAR(100) NOT NULL,
    CC_EN_NAME VARCHAR(100) NOT NULL,
    CC_TYPE    CHAR         NOT NULL,
    CC_TASKS   VARCHAR(500) NOT NULL,

    PRIMARY KEY (CC_SID)
);


CREATE TABLE BASSAM_FORMED_COMMITTEES
(
    SC_FORMATION_NO          BIGINT  NOT NULL,
    SC_COMMITTEE_ID          BIGINT  NOT NULL,
    SC_REWARD                BOOLEAN NOT NULL,
    SC_DECISION_NO           VARCHAR(30),
    SC_DECISION_DATE_AH      VARCHAR(15),
    SC_DECISION_DATE_AD      DATE,
    SC_FORMATION_END_DATE_AH VARCHAR(15),
    SC_FORMATION_END_DATE_AD DATE,
    SC_CREATED_BY            VARCHAR(8),
    SC_CREATED_DATE          VARCHAR(15),

    PRIMARY KEY (SC_FORMATION_NO),
    FOREIGN KEY (SC_COMMITTEE_ID) REFERENCES BASSAM_COMMITTEES (CC_SID)

);


CREATE TABLE BASSAM_COMMITTEE_MEMBERS
(
    CCM_SID              BIGINT NOT NULL,
    CCM_MEMBER_NID       LONG   NOT NULL,
    CCM_FORMATION_NO     BIGINT NOT NULL,
    CCM_ROLE_ID          INT    NOT NULL,
    CCM_DECISION_DATE_AH VARCHAR(15),
    CCM_DECISION_DATE_AD DATE,
    CCM_END_JOIN_DATE_AH VARCHAR(15),
    CCM_END_JOIN_DATE_AD DATE,
    CCM_STATUS           CHAR,

    PRIMARY KEY (CCM_SID),
    FOREIGN KEY (CCM_FORMATION_NO) REFERENCES BASSAM_FORMED_COMMITTEES (SC_FORMATION_NO),
    FOREIGN KEY (CCM_ROLE_ID) REFERENCES BASSAM_MEMBER_ROLES (CMR_ROLE_ID),
    FOREIGN KEY (CCM_MEMBER_NID) REFERENCES BASSAM_EMPLOYEES (EM_NATIONAL_ID)
);


CREATE TABLE BASSAM_MEMBER_ROLES
(
    CMR_ROLE_ID      INT NOT NULL,
    CMR_ROLE_AR_NAME VARCHAR(50),
    CMR_ROLE_EN_NAME VARCHAR(50),

    PRIMARY KEY (CMR_ROLE_ID)
);

CREATE SEQUENCE CMR_ROLE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE BASSAM_EMPLOYEES
(
    EM_NATIONAL_ID     LONG         NOT NULL,
    EM_FULL_NAME       VARCHAR(100) NOT NULL,
    EM_DEPARTMENT_NAME VARCHAR(60)  NOT NULL,

    PRIMARY KEY (EM_NATIONAL_ID)
);