DROP TABLE IF EXISTS PER_MODULES;
DROP TABLE IF EXISTS PER_MODULES_PERMISSIONS;
DROP TABLE IF EXISTS EMPLOYEE_RECORD;

CREATE TABLE PER_MODULES
(
    MODULE_ID BIGINT NOT NULL PRIMARY KEY,
    MODULE_ARABIC_NAME VARCHAR(50) NOT NULL,
    MODULE_ENGLISH_NAME VARCHAR(50) NOT NULL,
    MODULE_ICON_AWESOME VARCHAR(50) NOT NULL,
    MODULE_LINK VARCHAR(50) NOT NULL
);

CREATE TABLE PER_MODULES_PERMISSIONS
(
    MODULE_ID BIGINT NOT NULL,
    EM_NATIONAL_ID BIGINT NOT NULL,
    primary key(MODULE_ID,EM_NATIONAL_ID)
);

CREATE TABLE EMPLOYEE_RECORD(
    FULLNAME VARCHAR(100) NOT NULL,
    FULLNAMEEN VARCHAR(100) NOT NULL,
    EM_NATIONAL_ID BIGINT NOT NULL,
    EM_DATEOFBIRTH_AH VARCHAR(100) NOT NULL,
    EM_DATEOFBIRTH_AG VARCHAR(100) NOT NULL,
    EM_MOBILE_NO BIGINT NOT NULL,
    EM_DEPARTMENT_ID INT NOT NULL,
    DEPTSEC_NAME VARCHAR(100) NOT NULL,
    EM_ACTIVEDIRECTORY_UNAME VARCHAR(100) ,
    DEPTSEC_MANAGER_ID INT NOT NULL,
    DEPTSEC_NAME_ENG VARCHAR(100) NOT NULL,
    EM_JOBSYSTEM_ID INT NOT NULL
)
