DROP TABLE IF EXISTS CC_COMMITTEES;


CREATE TABLE CC_COMMITTEES
(
    COMMITTEE_ID BIGINT NOT NULL PRIMARY KEY,
    COMMITTEE_AR_NAME VARCHAR(50) NOT NULL,
    COMMITTEE_EN_NAME VARCHAR(50) NOT NULL

);